@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name login
POST http://{{host}}/api/auth/login
Content-Type: {{contentType}}

{
    "password": "asdf",
    "email": "fasihbaig_7@gmail.com"
}

###

@authToken = {{login.response.body.token}}

# @name allUsers
GET http://{{host}}/api/user
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}
