


POST http://localhost:3000/api/user/create
Content-Type: application/json

{
    "name": "fasih ullah",
    "username": "fasihbaig_7",
    "password": "asdf",
    "email": "fasihbaig_7@gmail.com",
    "gender": "male"
}


eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJmYXNpaF8yIiwiZmlyc3ROYW1lIjoiZmFzaWgiLCJsYXN0TmFtZSI6InVsbGFoIiwiZW1haWwiOiJmYXNpaF8yQGdtYWlsLmNvbSIsImlhdCI6MTcwMjIxNTU2N30.ekmG8D01zH5RLZTQfv1OuteFBHg1Ryo5bBL2moG_fu0