version: '1'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - /home/pie/mongoData:/var/lib/mongodb
    ports:
      - "27017:27017"