version: '1'
services:
  mongodb:
    image: mongo:latest
    container_name: todo-app-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - /home/pie/mongoData:/var/lib/mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: todo-app-redis
    ports:
      - "6379:6379"
