# Git workflow file deployment

name: Deploy to ECS Fargate

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.workflow_run.outputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deployment Info
        run: echo "Starting Deployment for Environment => ${{ github.event.workflow_run.outputs.environment }}"
        
