# Git workflow file for setting environment and deployment

name: Deploy to ECS Fargate

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.workflow_run.outputs.environment }}

    steps:
      - name: Deployment Info
        run: echo "Starting Deployment for Environment => ${{ github.event.workflow_run.outputs.environment }}"
      
