# Git workflow file for deployment to QA and Staging environment
name: Deployment Configuration Dispatch - AWS ECS
run-name: Deploy to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch: # This workflow will run manually
    inputs:
      environment:
        description: ' Drowpdown to select environment for deployment.'
        required: true
        type: environment

jobs:
  environment_validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Environment
        id: environment
        run: echo "Starting Deployment for Environment => ${{ github.event.inputs.environment }}"
        
  start_deployment:
        uses: ./.github/workflows/deployment-aws.yml
        with:
          environment: ${{ github.event.inputs.environment }}
